ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Uncomment when building for macOS with Catalyst
# ENV['RCT_BUILD_FROM_SOURCE'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'FabricExample' do
  config = use_native_modules!
  # Uncomment when building for macOS with Catalyst
  # use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => true
  )

  target 'FabricExampleTests' do
    inherit! :search_paths
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end

  # post_install for builds with catalyst enabled, due to a bug in hermes <=0.14.0
  # https://github.com/facebook/react-native/issues/55540
  # post_install do |installer|
  #   react_native_post_install(
  #     installer,
  #     config[:reactNativePath],
  #     :mac_catalyst_enabled => true,
  #     # :ccache_enabled => true
  #   )

  #   # ---- Hermes Mac Catalyst framework layout fix (RN 0.83.x) ----
  #   require 'fileutils'

  #   hermes_fw = File.join(__dir__,
  #     'Pods/hermes-engine/destroot/Library/Frameworks/universal/hermesvm.xcframework',
  #     'ios-arm64_x86_64-maccatalyst/hermesvm.framework'
  #   )

  #   if File.directory?(hermes_fw)
  #     Dir.chdir(hermes_fw) do
  #       # Ensure Versions/Current exists
  #       FileUtils.mkdir_p('Versions/A')
  #       File.symlink('A', 'Versions/Current') unless File.exist?('Versions/Current')

  #       # If top-level "hermesvm" is a real file, move it into Versions/Current and
  #       # replace with a symlink. This is the key part that prevents the "ambiguous" bundle.
  #       if File.exist?('hermesvm') && !File.symlink?('hermesvm')
  #         FileUtils.mkdir_p('Versions/Current')
  #         FileUtils.mv('hermesvm', 'Versions/Current/hermesvm')
  #         File.symlink('Versions/Current/hermesvm', 'hermesvm')
  #       end

  #       # Optional but makes the framework layout consistent
  #       FileUtils.mkdir_p('Versions/Current/Resources')
  #       if File.exist?('Resources') && !File.symlink?('Resources')
  #         FileUtils.rm_rf('Resources')
  #       end
  #       File.symlink('Versions/Current/Resources', 'Resources') unless File.exist?('Resources')
  #     end
  #   end
  # end
end
